version: 2

jobs:
  build:
    working-directory: ~/sonos
    docker:
      - image: liuchong/rustup:nightly
    steps:
      - checkout
      - run:
          name: Update all versions
          command: "rustup update beta && rustup update stable"
      - run:
          name: Install test-xunit
          command: "cargo install --git https://github.com/evernym/cargo-test-xunit"
      - run:
          name: Show toolchain versions
          command: "rustup show"
      - run:
          name: Build on stable
          command: "rustup run stable cargo build"
      - run:
          name: Test on stable
          command: "rustup run stable cargo test-xunit"
      - run:
          name: Build on beta
          command: "rustup run beta cargo build"
      - run:
          name: Test on beta
          command: "rustup run beta cargo test-xunit"
      - run:
          name: Build on nightly
          command: "rustup run nightly cargo build"
      - run:
          name: Test on nightly
          command: "rustup run nightly cargo test-xunit"
      - store_test_results:
          path: ~/sonos/test-results.xml
